name: Trackim
main: cn.cubegarden.trackim.Main
version: 1.0.0-SNAPSHOT
author: CubeGarden
api-version: 1.16

permissions:
  trackim.gui:
    description: 指南针打开GUI
    default: true

  trackim.cannottrack:
    description: 防止被追踪
    default: false